name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code 
      uses: actions/checkout@v2
      
    - name: Something
      run: echo "hah!"
      
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
